version: "3.4"

networks:
  newsapp:
    driver: bridge

services:
  newsappapi:
    container_name: news-app-api
    build:
      context: .
      dockerfile: NewsAppAPI/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - newsapp-db
    environment:
      - DB_HOST=newsapp-db
      - DB_NAME=CapstoneProjectDb
      - DB_SA_PASSWORD=${DB_SA_PASSWORD}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
    networks:
      - newsapp
    volumes:
      - logs:/newsapplogs
    command: ["dotnet", "NewsAppAPI.dll"]

  newsapp-db:
    container_name: newsappdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${DB_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    networks:
      - newsapp
    volumes:
      - db-data:/var/opt/mssql

volumes:
  logs:
  db-data:
