version: "3.4"

networks:
  newsapp:
    driver: bridge

services:
  newsappapi:
    container_name: news-app-api
    build:
      context: .
      dockerfile: NewsAppAPI/Dockerfile 
    ports:
      - 8000:80
    depends_on:
      - newsapp-db
      - kafka
    environment:
      - DB_HOST=newsapp-db
      - DB_NAME=CapstoneProjectDb
      - DB_SA_PASSWORD=Pass@123
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092  
    networks:
      - newsapp
    volumes:
      - logs:/newsapplogs
    command: ["sh", "/app/migrate-db.sh", "&&", "dotnet", "NewsAppAPI.dll"]

  newsapp-db:
    container_name: newsappdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Pass@123
      ACCEPT_EULA: "Y"
    networks:
      - newsapp
    volumes:
      - db-data:/var/opt/mssql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - newsapp

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - newsapp

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8081:8080
    extra_hosts:
      - "kafka1-nonesecure:130.1.1.1"
      - "kafka2-nonesecure:130.1.1.2"
      - "kafka3-nonesecure:130.1.1.3"
      - "kafka4-nonesecure:130.1.1.4"
      - "kafka5-nonesecure:130.1.1.5"
      - "kafka6-nonesecure:130.1.1.6"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - newsapp

volumes:
  db-data:
  logs:
