version: "3.4"

networks:
  newsapp:
    driver: bridge

services:
  NewsAppAPI:
    container_name: news-app-api
    build:
      context: .
      dockerfile: NewsAppAPI:/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - 
    environment:
      - DB_HOST=Capstone-Project-Db
      - DB_NAME=CapstoneProjectDb
      - DB_SA_PASSWORD=Pass@123
    networks:
      - newsapp
    volumes:
      - logs:/newsapplogs
  newsapp-db:
    container_name: newsappdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Pass@123
      ACCEPT_EULA: Y
    networks:
      - newsapp
    volumes:
      - db-data:/var/opt/mssql
volumes:
  db-data:
  logs: